apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  annotations: {}
  name: default
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-tf-aws"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }
    provider "aws" {
      access-key = ""
      secret-access-key=""
    }
